### ISSUE TITLE
A secondary way to request plugins

### ISSUE THREAD

**Issue by quick007** [Minehut/Meta#191]
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**
Website?

**Describe the feature**
Add a better way to suggest plugins (maybe a g form). It feels kinda janky just posting a thread and hoping the plugins get added. (even if we use an auto-updater , we still need a way for people to suggest plugins)

**How the feature is useful**
Would make it easier for you guys to see plugin requests (on a google sheet/excel) and would make suggesting plugin additions/updates for people.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by PundaChen** [comment]
Should suggest an example of what kinds of things they can use, I personally think that the forums is fine but would love to hear about some ideas you might have!

**Comment by LukasmanMHdude** [comment]
> Should suggest an example of what kinds of things they can use, I personally think that the forums is fine but would love to hear about some ideas you might have!

The forums work, but it would be easier on our and their side to suggest plugins, as on a form you can ask questions instead of using a format.

**Comment by pop4959** [comment]
As the new content manager, here's my 2 cents on this. I don't actually think the forum is so bad, it's just that there was not anyone available to fully dedicate their time to reviewing and updating plugins before. Since that's my role, you can probably expect more frequent updates now, with most of the plugins you expect to see.

I'm not actually a huge fan of Forms for this, as you lose out on some of the community involvement that actually helps content managers do their job, such as people commenting/voting on plugins they're interested in, and mentioning if there are certain issues in updating those plugins.

If anything, Github would probably be a better platform to move to. It's designed for issue management (people asking to update broken plugins) and feature requests (for new plugins) which can easily be labeled and voted on, as well as having a community thread where people can discuss the issues they are experiencing currently with the plugins. Templates can be used to make sure people fill out all of the proper information that is necessary.

Best have a bit more discussion on this, as I'd love to hear what everyone thinks is best for the community.

Again though, I think the forums is fine for the time being, and I don't personally see any rush to change it. However, in the long term I can definitely see this getting changed, especially if Minehut goes more in the direction of semi automating plugin updates to make to make the process even faster.

**Comment by Blocksnmore** [comment]
Honestly i feel the way requests on the forum should be redone, 2 categories, Plugin requests and Plugin updates, to have plugins that are popular have a higher chance of being added instead of being buried down Plugin requests

**Comment by LukasmanMHdude** [comment]
> As the new content manager, here's my 2 cents on this. I don't actually think the forum is so bad, it's just that there was not anyone available to fully dedicate their time to reviewing and updating plugins before. Since that's my role, you can probably expect more frequent updates now, with most of the plugins you expect to see.
> 
> I'm not actually a huge fan of Forms for this, as you lose out on some of the community involvement that actually helps content managers do their job, such as people commenting/voting on plugins they're interested in, and mentioning if there are certain issues in updating those plugins.
> 
> If anything, Github would probably be a better platform to move to. It's designed for issue management (people asking to update broken plugins) and feature requests (for new plugins) which can easily be labeled and voted on, as well as having a community thread where people can discuss the issues they are experiencing currently with the plugins. Templates can be used to make sure people fill out all of the proper information that is necessary.
> 
> Best have a bit more discussion on this, as I'd love to hear what everyone thinks is best for the community.
> 
> Again though, I think the forums is fine for the time being, and I don't personally see any rush to change it. However, in the long term I can definitely see this getting changed, especially if Minehut goes more in the direction of semi-automating plugin updates to make the process even faster.

I totally agree with that. (The GitHub part at least) It would reduce spam and make stuff actually searchable. Also would let people easier find out what plugins are already requested. But speaking of making sure people don't double suggest plugins,  It would be cool to have a google sheet (easy to find, maybe pinned to the top of the git) that would list all the plugins that are color-coded to show updating and stuff. (i.e. green = recently updated, blue = in the process up updating, and so on) I know this may seem redundant, but having easy access to all the plugin related stuff would be very helpful. Maybe a bot could help with this?

Secondly, plugin deletion. While I know this may sound controversial, there are some plugins we really don't need, especially ones that are built into vanilla Minecraft. (if it's in vanilla, it will be more stable anyways). It also just makes sense to get rid of plugins that are broken cause of lack of updates from the of dev, or just generally bad ones that have little to no use (i.e. creating a plugin that toggles a gamerule)

Third, recommended plugins. I suggested this a while ago [here](https://discordapp.com/channels/546414872196415501/592130982451216402/736357516887457864), and it got decent feedback from the community (and I think Trent may have said smth about it as well). It would really help the fact that you can look up plugins, and get like 5 results, and not knowing which one is the best. I see lots of people install "bad" plugins that hurt performance and aren't that great.

**Comment by LukasmanMHdude** [comment]
also, what do you think about adding dev builds (i.e. when mh updates to 1.16 and we need w/g on our server, we could have a button that allows us to use a semi-stable dev build instead of the older stable 1.15 version). This would really only be plausible for you with auto-updates tho.

**Comment by pop4959** [comment]
> also, what do you think about adding dev builds (i.e. when mh updates to 1.16 and we need w/g on our server, we could have a button that allows us to use a semi-stable dev build instead of the older stable 1.15 version). This would really only be plausible for you with auto-updates tho.

Already got approval for that. In fact, 4 out of the 8 plugins updated this past Thursday were dev builds. 😉

**Comment by BennyDoesStuff** [comment]
With the implementation of custom plugins, this is no longer an issue as you can simply upload any plugins that don't exist on the addons list.
