### ISSUE TITLE
Version switcher

### ISSUE THREAD

**Issue by Blocksnmore** [Minehut/Meta#20]
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**

Block game (java)
**Describe the feature**

Change versions
**How the feature is useful**

Some servers would prefer if they had the ability to use a version like 1.8 for example over the latest version, with this when you create a server you can change the version the server runs on.
---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by WallyTube** [comment]
Nice idea, but this is a dupe of my thread and with dryer detail

**Comment by jellz** [comment]
@WallyTube I believe this issue was made before yours?

**Comment by Blocksnmore** [comment]
Yup it was made before

**Comment by WallyTube** [comment]
Mines a tad different, it just involves the same stuff.

**Comment by drtshock** [comment]
Yes we could do this. If we did, it would be the same work that would also include:
- different plugin versions (a lot more for us to manage)
- support for snapshots / newer versions
- support for modded servers

If we did this, should we auto upgrade servers on version updates, or should we notify them when a new version is available and just have new servers created since then default to latest?

**Comment by hriaksnv5678** [comment]
Is there a reason you have to check every plugin? Other than file management what could really be exploited. if you set file management to just not work by denying the files to the user (I'm assuming its linux) then you probably wouldn’t need to modify those plugins.

If this was it, you could expand the list of supported plugins as well as allowing multiple versions by maybe downloading them from some api (does spigot have a downloading api??) and cache them instead of manually updating and hosting them.

And on the topic of what you asked, I think there should be a version selector, and if you pick a snapshot or latest version, it gives you the option to “auto upgrade” or just notify them and do it manually. This could work as it would be less thinking for people with simple desires just wanting a up-to-date server, and also works for the people building more advanced servers.

**Comment by Blocksnmore** [comment]
> Does spigot have a downloading api
They dont have an official one (iirc) but there is a version called spiget which i belive is open sourced

**Comment by hriaksnv5678** [comment]
https://papermc.io/api/v1/paper

to get version array, then we can just do https://papermc.io/api/v1/paper/<version>/latest/download

**Comment by iGalaxyYT** [comment]
> https://papermc.io/api/v1/paper
> 
> to get version array, then we can just do https://papermc.io/api/v1/paper/[version]/latest/download

This is to download Paper's server jar, not Spigot plugins.

**Comment by Robomnz** [comment]
i hope this would include snapshots if we are able to choose version

**Comment by WallyTube** [comment]
> Is there a reason you have to check every plugin? Other than file management what could really be exploited. if you set file management to just not work by denying the files to the user (I'm assuming its linux) then you probably wouldn’t need to modify those plugins.
> 
> If this was it, you could expand the list of supported plugins as well as allowing multiple versions by maybe downloading them from some api (does spigot have a downloading api??) and cache them instead of manually updating and hosting them.
> 
> And on the topic of what you asked, I think there should be a version selector, and if you pick a snapshot or latest version, it gives you the option to “auto upgrade” or just notify them and do it manually. This could work as it would be less thinking for people with simple desires just wanting a up-to-date server, and also works for the people building more advanced servers.

Apologies if I'm necroposting, but this doesn't exactly work. Minehut has to screen plugins to make sure they aren't malicious, and some plugins have their own forks made for minehut. We can't just take the newest version of skript and drag and drop it into a folder.

**Comment by CoreyShupe** [comment]
Implemented.
