### ISSUE TITLE
Legacy Panel Theme

### ISSUE THREAD

**Issue by farwl** [Minehut/Meta#211]
### Feature request

**Platform**
 Website

**Describe the feature**

I think it would be sick if we could get this clean, slick design back for the web panel. 
![](https://puu.sh/yX0yk/2b98d02453.png)
This was originally used back in 2018 / 2017 for some time.

**How the feature is useful**

This benefits everyone by providing them with a cleaner, more user-friendly panel.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by drtshock** [comment]
We're not going to add support for a legacy panel, but we're definitely looking to improve upon the current panel. So any suggestion along those lines are welcome. We're already not updating our 1 theme enough, so adding a second theme would increase the work.

**Comment by farwl** [comment]
No I'm saying switch back to this theme @drtshock

**Comment by iGalaxyYT** [comment]
> No I'm saying switch back to this theme @\drtshock because let's be honest; Nobody likes the current theme or the layout. It's not easy to look at or user-friendly. This theme/layout from 2018 is.

I like the current panel. Looks much better and much more like modern web design.

**Comment by farwl** [comment]
The current dashboard is hideous sorry

**Comment by iGalaxyYT** [comment]
> The current dashboard is hideous sorry

What's so hideous about it?

**Comment by farwl** [comment]
> What's so hideous about it?

Glad you asked -

1. Colors do not compliment each other. Some are far darker than others and it generally does not look nice or pleasing.
2. Top navbar is weirdly enlarged because of a useless breadcrumb which doesn't work for your server files, just says "Editing Server"
3. Sidenav is glitchy when hovering, and doesn't remember if you had it expanded or collapsed.
4. There are an INSANE amount of ads on the panel.
5. Dashboard home could be improved. The list of owned servers seems overly large for no reason.
6. The UI of the current dashboard is not a slick/clean design or very easy to use. The screenshot I have above looks far simpler and easy to use.
7. The Shop item should not have a dropdown in the sidenav, as it already leads to the shop page where you can navigate to a sub-section of the shop.
8. When clicking on the Shop dropdown in the sidenav it creates a random scrollbar inside the item which looks pretty ugly.
9. There is no padding between the page content and the sidenav which causes the content not to be centered properly. In the old panel design, the content is centered on the page.

cba to list more. The generally point I'm trying to convey is that the panel used to be much simpler, cleaner, and have more of a slick design / layout. It was more user friendly by far and I think it would be more preferred than the current dashboard.

**Comment by iGalaxyYT** [comment]
Here's my response -
1. I would say that the colors are much better, old design had more variation in the colors (black, white, blue) while the new design just has black/gray and blue.
2. I agree with this one, there should be a toggleable option to hide the breadcrumb.
3. Sidebar bug was fixed, not sure why it's still bugged out for you. Only complaint I have about the sidebar is #221.
4. Can be fixed using an adblocker.
5. I agree with this one, there should be a "compact" home design with cards for the servers instead of them being very wide. It's still better than the old design in my opinion though, as the old design had you switching between servers using a dropdown.
6. The design of the file manager hasn't really changed, other than the bulky server information being at the top. I wish there was an option to hide it.
7. I agree with this one, the shop shouldn't have a dropdown.
8. Yeah, I'm assuming that's a bug and should be reported. I believe it's caused by the sidebar items going out of the boundary.
9. I agree with this, page content is way too stretched out.

Other than that, the components look much nicer than the old panel design. It's just the way that they're laid out is the problem. I don't think the new panel is any less user friendly than the old one. I have an idea for a way to customize the layout of your dashboard that I'll be making an issue for soon.

**Comment by WallyTube** [comment]
1. I absolutely hate minehut's color scheme right now. The older one was better. It looks like window's command prompt, but 3x worse.  The old color scheme was too warm. If minehut just used discord's color scheme it would look so much better.
2. The breadcrumb is useless right now. I don't use it, and Idk anyone else that uses it either. If the breadcrumb showed each folder of the file manager instead of what server you are editing, I might actually use it, but even then, it shouldn't be inside of the topnav.
3. I hate how the sidenav pops out. If minehut could just put all of the sidenav stuff into the topnav and gotten rid of the stupid sidenav hover, it would look and be so much better.
4. Minehut needs ads for money, and all ads in general are an inconvenience, so I agree with galaxy. Use an ad blocker.
5. It ultimately just needs to be centered, and maybe go 2 or 3 servers per row instead of stacked on top of one another. Also, the animation for reordering servers is crap, and the 6 circles at the top looks unprofessional. If they just made a vertical white line in the center of that tab, it would look better, but even then, doesn't seem like the best solution.
6. The old panel looks worse than the new one. I don't see anything on the old panel that is so much better. They just need to put the sidenav stuff in the topnav, and maybe make the options at the top of  a server like file manager, plugins, etc. stick to the topnav when scrolling down.
7. I don't use the shop, but I agree. Also, marketplace should be put inside of shop the marketplace tab is useless right now, and would take up space if they added it to the top nav.
8. This happens because your browser is set to zoom in 100% or more. I set my browser zoom to 90%, and I don't have this problem.
9. This goes with my thought for Number 5.

Ultimately, Minehut isn't listening to the large majority. It seems like they are finding the smallest, easiest projects that one person suggested, and ruining the feel of the webpage for everyone else. Minehut's main webpage looks 110% better than the panel.

**Comment by KikoPT1234** [comment]
> Minehut's main webpage looks 110% better than the panel.

Agreed, and they're using the same framework! Whoever is making the panel right now, please listen to our feedback.
Or maybe don't use Vuetify and start being more creative? I find web design very easy and honestly don't see how they could mess up this badly.

**Comment by MrScopes** [comment]
would be cool if they added several options for different themes

**Comment by Double0negative** [comment]
While different themes could be a cool feature, right now we need to focus on improving our current theme and bringing new features to our players. Thank you all for your suggestions on improvements, they will be noted as we continue to improve the site.
