### ISSUE TITLE
Don't attempt to connect people to servers they can't play on

### ISSUE THREAD

**Issue by LukasmanMHdude** [Minehut/Meta#226]
### Feature request

**Platform**
ingame, both

**Describe the feature**
Dont send ppl to servers they can't play on

 - Recently start/turning off ones that throw out errors
 - Ones with whitelists
 - Ones that can't support your version

Just say "We can't connect you right now", and also try and put a better message then the weird errors bungee throws out.

**How the feature is useful**
Makes it so people don't have to jump between lobbies when trying to connect them to a server.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by Blocksnmore** [comment]
Semi Dupe of #29

**Comment by LukasmanMHdude** [comment]
This encompasses all of them, and I just wanted to put them in one place

**Comment by Blocksnmore** [comment]
You should just write a comment on that issue instead of opening a new issue

**Comment by LukasmanMHdude** [comment]
I could, but this works just as well and (hopefully) brings more attention to the issue because

**Comment by theminecoder** [comment]
So there's a couple of inherent problems with this. By design we don't track player server whitelists and what functionality plugins add to the server, as it can vary from server to server. People even sometimes implement their own whitelist system by ways of permissions. So we are unable to precheck those when sending people to a server.

However the recently started & lobby jumping when trying to connect would likely be classified as bugs so I think if you were to update the issue to reflect that or open a new one & close this we can mark it as such :)

**Comment by LukasmanMHdude** [comment]
Ok, yea the lobby moving disconnect this is really the only problem, I'll make a bug report soon:tm:
