### ISSUE TITLE
Please Test Events

### ISSUE THREAD

**Issue by LukasmanMHdude** [Minehut/Meta#261]
### Feature request

**Platform**
Ingame

**Describe the feature**
If you're planning out an event, please make sure to **TEST** out these. Do a "beta" for 3 or 4 days. If you are getting paid to host these they should be playable.

**How the feature is useful**
Sponsors get a functioning game, and players can actually play it.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by MiginsMC** [comment]
Reason @Double0negative ??

**Comment by jellz** [comment]
Also curious why the webhook message for this issue close was deleted from the channel 🤔

**Comment by ItzOP** [comment]
@Double0negative Closed this with no explanation, so I'm going to just state my points of few anyway.
I think if a staff closes something they should explain it first.

Anyway, I personally know they do test many of the events, I've been asked to participate in a few of them and they do fix a majority of bugs during that time. Although we somehow see major bugs in events despite this testing, I think this is because after the test they start fixing bugs but also majorly change the code and never have a second testing session for that.

**Comment by LukasmanMHdude** [comment]
I think it would be nice to do a full community test, to stress test the servers and whatnot. If they do tests, they need to advertise them better cause I've never seen them.

**Comment by WallyTube** [comment]
You also have to consider the fact that minehut's sponsors are earning more from this than minehut is. Hence why minehut isn't just giving out credits to the winners of the soccer city participants or the escape room participants. Also, it may not be in minehut's best interest to spend time in something that isn't going to benefit their overall service, including a temporary event

**Comment by LukasmanMHdude** [comment]
Come on, it takes 3 days to test an event. I should of made this bug report a few days earlier: #258 (also note that I can't even join the games sometimes, which is like WhAt ThE f)
