### ISSUE TITLE
Moving suggestions back to Discord

### ISSUE THREAD

**Issue by PundaChen** [Minehut/Meta#278]
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**
Meta Discord

**Describe the feature**
Move suggestions back to the Meta Discord, create new channels for suggestions and start actively deleting any repeated suggestions.

**How the feature is useful**
- You get more votes, the github gets around 3-5 votes at most, most of the Discord suggestions got 20-40 votes, which will be more now since there aer way more users in the Discord
- Better feedback, the Discord always had long conversations about the suggestions that were being made, suggestions would be edited occordingly and people would be able to understand eachother a lot more
- Promote activity in the Meta Discord again, Meta really only gets used for testing nowadays, the Discord is extremely inactive and because of this tests will get less users
- You get more suggestions, a lot of users including myself do not enjoy going out of their way to suggest things, especially when you try to mass suggest things it becomes really difficult to do, a lot more users will be willing to suggest things if it was brought back to the Discord server

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by MiginsMC** [comment]
On github comments/conversations are specific to the suggestion so it's considerably easier to collate ideas and communicate these with devs. On discord the suggestion discussions are in one channel and it's almost impossible to read back on these conversations without spending quite a while scrolling through the channel.

**Comment by Sniped** [comment]
Overall, GitHub is definitely a better solution than Discord as of right now. Developers are able to overlook all suggestions in bulk and there's overall just better moderation of suggestions than there were on Discord. We're able to preserve every suggestion and its conversations without having to look back onto the Discord server's clutter of conversations. 

How would we be able to apply this functionality to Discord if we ever were able to go back? What sort of stuff would we need to be able to categorize specific suggestions and their threads without having to look back at the clutter of conversations about such a suggestion? How would we be able to keep people on-topic with a suggestion? Frequently, people in the discussions channel often swayed away from a specific suggestion and talked about nothing. When we get past that, how will admins be able to look back at suggestions in bulk and reply as necessary? How would these "official responses" get out to the community? 

In my opinion, Meta isn't degrading in member retention and available tests will still be conducted with decent success. The Discord currently has 617 members with 612 of them being online this week. That means that if we were to ping everyone in that Discord we would likely get a good amount of respondents. In terms of more suggestions, I believe that quality is better than quantity. A vast amount of suggestions on Meta were duplicates causing even more disorganization. We could try and potentially block duplicate suggestions if we were to ever integrate back into Discord, however is it really worth it? Even if we were to disregard the problem of duplicate suggestions, how many of the suggestions in the Discord would simply be vague, unrefined ideas? With GitHub, users can express why a suggestion should be added and have the chance to refine it and convince developers and players alike why it's a good addition. On Discord we could enforce a format similar to GitHub's and make the process interactive with the bot, but again is it really worth it to do that?

The integration of GitHub has definitely improved the process from what it was back then. I'm not saying I don't completely disagree with going back to Discord, it's just a matter of how it would be integrated back into Discord without it being as unorganized as it used to be. It's also a matter of if it's actually beneficial for us to move back to Discord, because as explained here there are a lot of things that GitHub offers that Discord doesn't despite it's drawbacks with votes on suggestions and such.

**Comment by jellz** [comment]
I agree with Facto on most of his points, and there is a definite fact: If Minehut Meta was to use Discord to process issues again, it would definitely need to be a different system

**Comment by Shlba** [comment]
I agree with Emily here - we aren’t really getting many suggestions here compare to when it used to be done on the discord. Many people just can’t be bothered to make a Github account just to add a idea that probably would never be considered. Overall, using the discord is just more convenient and simple for the average user- much less complicated.

Potential solutions for problems:

- there could be a system where suggestions with a lot of upvotes could be displayed, which would allow developers to see suggestions that users would like to see implemented

- a more active meta staff team patrolling and noting down insightful suggestions 

Just a few ideas I came up in the span of a **single** minute. Many better solutions can still be found

**Comment by PundaChen** [comment]
Imma quickly add onto this, this was suggested in #meta-feedback and got 17 upvotes (+2 downvotes) which is more votes than any suggestion here will get if I may say so as well

**Comment by Shlba** [comment]
I mean, yea, after all, the meta discord and services were all made to get feedback from the community, so restricting that really defeats the purpose of that. As most wouldn’t bother to make a GitHub account just to post a suggestion, you effectively lock out suggestions to only the most dedicated members of the minehut community, and not the casual player with a fun idea

**Comment by PundaChen** [comment]
> I mean, yea, after all, the meta discord and services were all made to get feedback from the community, so restricting that really defeats the purpose of that. As most wouldn’t bother to make a GitHub account just to post a suggestion, you effectively lock out suggestions to only the most dedicated members of the minehut community, and not the casual player with a fun idea

Honestly, if I didn't already have a GitHub account, I don't think I would've made one for suggesting things, I've met multiple other users who feel the same way

**Comment by jellz** [comment]
I definitely think it is worth exploring returning to Discord for processing issues, there is a clear exposure problem and barrier to entry problem with GitHub

**Comment by Shlba** [comment]
> > I mean, yea, after all, the meta discord and services were all made to get feedback from the community, so restricting that really defeats the purpose of that. As most wouldn’t bother to make a GitHub account just to post a suggestion, you effectively lock out suggestions to only the most dedicated members of the minehut community, and not the casual player with a fun idea
> 
> Honestly, if I didn't already have a GitHub account, I don't think I would've made one for suggesting things, I've met multiple other users who feel the same way

**EXACTLY**

**Comment by Sniped** [comment]
Well when Meta was first created it went like this:
- A few members of council were appointed at random (later they were appointed by how much they contributed to discussions in that week)
- Suggestions were suggested, and the bot kept track of upvotes and downvotes for suggestions and sorted them.
- Every week or two (on a Sunday mostly), the council got together and discussed suggestions and refined them on a Google doc. This doc was sent out to Trent for him to critique and such and it was publicly exposed to the community.

If enough people were to contribute to discussions each week and there were enough for council members to be appointed, then I would believe it would be beneficial. However, with long trails of suggestion conversations, how exactly will a suggestion evolve with it? Will the user that made the suggestion just edit their message? Should this old council still be appointed every one or two weeks or should it be dedicated to Meta staff? Speaking of which, would they just have to go through and look for duplicate suggestions of some hundreds of messages in a Discord channel? 

A few improvements that might address these concerns are as follows:
- Users can request edits of a specific question that are approved by a Meta staff. It would go through an approval queue where staff can just accept or deny an edit. Something else to note here is how would they know if it pertains to the current conversations that are going on? Would it be their job to follow the conversation and judge it that way? Or should it only be up to Meta staff to go through conversations and actively record edits?
- The bot can try to identify possible duplicates with suggestions and notify Meta staff for them to look at as sort of a "pending" suggestion. Once they approve it, it would end up on the stream of suggestions, however if they deny it, it wouldn't show up at all.
- Rather than appointing a council, Meta staff could be integrated into the staff team or even allow community members to apply and integrate it into the Nexus discord server we use. 
- We use Trello rather than Google docs to refine suggestions as we feel are needed during weekly / biweekly meetings that may occur. 

In all of this, is it worth the effort to convert the recently released issue tracker back to Discord? Not only would we have to develop and integrate this system into the bot, we would also have to port issues back to Discord and (maybe) categorize them considering their labels. Even regarding labels, should a Discord system try and replicate labels? Can we get on par with the labeling that GitHub allows? It allows for filtering of suggestions that pertain to a certain category. For example, if I want to look at bot suggestions, I can just click on the label in the issues list and it'll give me all suggestions related to it. Would we be able to get this kind of filtering on Discord? We would also be sacrificing threaded conversation, which despite having addressed earlier in this reply, would likely be a huge drawback.

**Comment by LukasmanMHdude** [comment]
I can see both sides of this, but the meta discord is really for bug reporting, trying to get unmuted, but mainly Suggesting and trying to get new features added. Discord, while maybe doesn't have comment threads (maybe soon:tm:?) has a lot of other features that allow us to communicate, but mainly a much bigger community. As stated above, there is wayyyy more feedback on discord then on Github. This lets a bigger portion of the community give insight into what they want. The idea of a trello board allows us to show the dev's what we want easier as that was one of the reasons for us to move to Git,it also has a lot of other features that would help with suggestion moderation and whatnot.

**Comment by LukasmanMHdude** [comment]
I also know that this suggestion I'm making here may get some hate, why I decided to not post it with the thread above:

Move suggestions to discord, but keep bug report here, so that more people can accurately comment on them, people can be assigned to them, and Git is just a better place for bug reports ngl.

(Vote on this ig?? Don't think this warrents a new suggestion, so would like to see some feedback in the form of :+1: and 👎)

**Comment by jellz** [comment]
Once I get home today I will go through some concerns I have and potential ways we could make a good return to Discord for processing issues. This will require a lot of brainstorming however.

**Comment by Sniped** [comment]
Would still like feedback on [this](https://github.com/Minehut/Meta/issues/278#issuecomment-695751276)

**Comment by Shlba** [comment]
> * Users can request edits of a specific question that are approved by a Meta staff. It would go through an approval queue where staff can just accept or deny an edit. Something else to note here is how would they know if it pertains to the current conversations that are going on? Would it be their job to follow the conversation and judge it that way? Or should it only be up to Meta staff to go through conversations and actively record edits?

- Having an approval system for editing suggestions would make it very difficult for staff members. This may be simply because of the sheer number of suggestions submitted which require editing.

> * The bot can try to identify possible duplicates with suggestions and notify Meta staff for them to look at as sort of a "pending" suggestion. Once they approve it, it would end up on the stream of suggestions, however if they deny it, it wouldn't show up at all.

- This I have nothing against.

> * Rather than appointing a council, Meta staff could be integrated into the staff team or even allow community members to apply and integrate it into the Nexus discord server we use.

- I feel like theres already a lot of responsibilities that staff members have to fulfil, so giving them this many would just burden them more than it would help with suggestions. Having a dedicated team would be the best suited for this job as they can dedicate all of their time towards curating suggestions and managing the discord. 

> * We use Trello rather than Google docs to refine suggestions as we feel are needed during weekly / biweekly meetings that may occur.

- Yea, This I have nothing against as well

**Comment by Sniped** [comment]
> I feel like theres already a lot of responsibilities that staff members have to fulfil, so giving them this many would just burden them more than it would help with suggestions. Having a dedicated team would be the best suited for this job as they can dedicate all of their time towards curating suggestions and managing the discord.

That's what I meant by it, it would be like the Events Team or the Creative Team where staff and players alike could join it. Maybe have senior staff that could dedicate themselves to seeking out potential staff members (or maybe even have this as the council). 

> Having an approval system for editing suggestions would make it very difficult for staff members. This may be simply because of the sheer number of suggestions submitted which require editing.

Then do you believe Meta Staff should be tasked with following a conversation and editing a suggestion if necessary? If not, how do you feel a suggestion can be evolved by discussion without something like an edit command being abused by everyone?

**Comment by RichieNy** [comment]
> > * Users can request edits of a specific question that are approved by a Meta staff. It would go through an approval queue where staff can just accept or deny an edit. Something else to note here is how would they know if it pertains to the current conversations that are going on? Would it be their job to follow the conversation and judge it that way? Or should it only be up to Meta staff to go through conversations and actively record edits?
> 
> * Having an approval system for editing suggestions would make it very difficult for staff members. This may be simply because of the sheer number of suggestions submitted which require editing.

* We could come up with a system to help make it easier for staff to go through suggestions. In addition, Community Meta Staff **could** become a thing in the future to help take the load off of Minehut Staff.

> > * Rather than appointing a council, Meta staff could be integrated into the staff team or even allow community members to apply and integrate it into the Nexus discord server we use.
> 
> * I feel like theres already a lot of responsibilities that staff members have to fulfil, so giving them this many would just burden them more than it would help with suggestions. Having a dedicated team would be the best suited for this job as they can dedicate all of their time towards curating suggestions and managing the discord.

* Currently, the Meta Staff has members who actually want to help and participate. In addition, I do agree with the idea of having a Team and possibly a Senior Moderator in charge.

**Comment by Shlba** [comment]
> Then do you believe Meta Staff should be tasked with following a conversation and editing a suggestion if necessary? If not, how do you feel a suggestion can be evolved by discussion without something like an edit command being abused by everyone?

- If the meta team was a dedicated team for handling suggestions, then I would be more than happy to believe that the meta team could be tasked with handling and documenting suggestions if necessary.

**Comment by ItzOP** [comment]
I've read through quite a lot of this and strictly from my perspective I still think GitHub is better.

- You always get a response from a meta staff member, which makes your suggestions feel meaning full and like they're actually being listened to.
- It's easier for the meta staff to view and keep track of suggestions here.

And the biggest and only negative I've really seen is the lack of users on the github to vote.
Personally I think we need two channels to separate out the initial suggestions and comments.
Some new suggestions get over run by people commenting on old suggestions.
I vote on suggestions when I see them in the #issues discord channel but often it's just people commenting on old posts.

I think that alone would definitely increase the amount of things people vote on.

**Comment by Shlba** [comment]
> - You always get a response from a meta staff member, which makes your suggestions feel meaning full and like they're actually being listened to.

- most only get a response if they are denied

>  - It's easier for the meta staff to view and keep track of suggestions here.

- Meta staff members would also have a easy time keeping track of suggestions if they used the discord system suggested above

**Comment by ItzOP** [comment]
> * most only get a response if they are denied
Not particularly, I've seen many staff respond and talk about suggestions before denial or acception.

> * Meta staff members would also have an easy time keeping track of suggestions if they used the discord system suggested above
"easy time", but they would have an easier time on github in general.
Discord isn't made for this type of thing and anything you do to make it more tolerable in discord is just attempting to make it closer to GitHub. Which doesn't make sense when we already have GitHub to work with.

**Comment by PundaChen** [comment]
> You always get a response from a meta staff member, which makes your suggestions feel meaning full and like they're actually being listened to.
It's easier for the meta staff to view and keep track of suggestions here.
Easier for people to comment and talk about 1 specific suggestion without it getting lost.

You actually quite often got a response in the discord, if anything more staff talked in there than they use github now
It's not difficult to keep track of suggestions on discord, it's messier on github tbh because the pages get confusing imo
Also you can just quote the suggestion you're talking about and people will just follow the convo

**Comment by jellz** [comment]
Suggestions and bug reports definitely get more admin attention on GitHub

**Comment by ItzOP** [comment]
> 
> You actually quite often got a response in the discord, if anything more staff talked in there than they use github now
> It's not difficult to keep track of suggestions on discord, it's messier on github tbh because the pages get confusing imo
> Also you can just quote the suggestion you're talking about and people will just follow the convo
I never received responses in discord, despite many of my suggestions getting more than 20 upvotes.
In GitHub I've always received a response and I've seen so many other get a response.
Especially from higher up's which you don't see much on discord.

Even when quoting a suggestion, the chat moves on eventually or quickly and your conversation about that suggestion is lost further up in the channel whereas on GitHub they are obvious and under the suggestion you are talking about.

And the pages are easy to navigate once you get use to GitHub, but this is one thing I can agree on, it is confusing for new people who haven't used GitHub before.

**Comment by ItzOP** [comment]
> Suggestions and bug reports definitely get more admin attention on GitHub.
> 
> I was thinking about the low voting problem, and I do think a channel which only showed new suggestions could be good. I think we should try to focus on making it easier to vote on suggestions, like maybe without a GitHub account somehow.

That sounds good.
You could just scrap the voting function on github and add yes/no reactions to suggestions that come through in an issues channel on discord.

**Comment by jellz** [comment]
Maybe we could build our own web platform that allows Discord sign in which is much more intuitive for users? I’m thinking with things like:
- Instead of text templates, could be a form and actual check boxes
- Discord sign in
- We could let users vote on and even submit suggestions from Discord
- Better, easier UI and UX

And we’d have more control over the things that GitHub doesn’t let us change.

**Comment by Sniped** [comment]
> Maybe we could build our own web platform that allows Discord sign in which is much more intuitive for users? I’m thinking with things like:
> 
> - Instead of text templates, could be a form and actual check boxes
> 
> - Discord sign in
> 
> - We could let users vote on and even submit suggestions from Discord
> 
> - Better, easier UI and UX
> 
> 
> 
> And we’d have more control over the things that GitHub doesn’t let us change. 
> 
> 
> 
> This was just a quick thought I had, there's much more I could go into if we want to explore this idea.

I suggested something similar to this quite a while back. We can definitely explore this idea, however how would this deal with the synergy between a website and Discord?

**Comment by PundaChen** [comment]
I'm pretty sure barely anyone wants to go on some site just to suggest something
Last time everyone agreed that just having a bot for suggesting would be the best choice and that was a great option

**Comment by Sniped** [comment]
I imagine both a website and discord would allow for people to suggest and vote on discord and the website equally. If not, then we should use a website and discord and have them communicate with each other in my opinion.

**Comment by jellz** [comment]
Personally I think using a website offers many great benefits, like labels and individual discussions. But as I said, I’d still be open to exploring a Discord-only system.

**Comment by RichieNy** [comment]
> Personally I think using a website offers many great benefits, like labels and individual discussions. But as I said, I’d still be open to exploring a Discord-only system.

Maybe creating a Meta Bot which can log all suggestions in embeds as well as add labels? That seems like a good approach we could take if we decided to switch back to discord.

**Comment by jellz** [comment]
Logging issues as embeds won’t organise the discussions

**Comment by Sniped** [comment]
A few ideas that I have that would help out with making a website that includes Discord:

- Allow people to comment on ideas both on the Discord and this propose website. Users would be able to comment on suggestions on the website and they would also be able to comment by making referencing the issue. For example, if I wanted to comment on suggestion #1, I would simply just say `#1 I think this suggestion is very cool!`.
- Be able to filter suggestions both on the website and on Discord. To filter suggestions by a label, you could type in `!suggestion filter discord`. 
- Sorting suggestions both on the website and on Discord.

**Comment by jellz** [comment]
I don’t think people should be able to comment through Discord. Not only would it be weird but the channel would just be full of seemingly incoherent statements.

**Comment by Sniped** [comment]
In my opinion it would also be weird to be able to suggest something on the Discord then have to go comment about it on an external website. We can always delete the references to the suggestions and DM the user that they successfully were able to comment.

**Comment by jellz** [comment]
A new post doesn’t require context. Comments require context and reading of the other comments in the thread, which you wouldn’t do on Discord

**Comment by Sniped** [comment]
Yeah, that's true, but at that point I don't see a lot of users going onto this website and commenting after someone makes a suggestion on Discord.

**Comment by jellz** [comment]
By make suggestion on Discord thing I just mean submitting it through a prompt in DMs.

**Comment by Sniped** [comment]
Ah, then I assume it would just submit to GitHub or some external source? How would we handle upvotes and downvotes for suggestions then? Just on an external website?

**Comment by Shlba** [comment]
"Github simply cannot be utilised as a method of submitting suggestions" - my irl friend harshly said when viewing this page

**Comment by Sniped** [comment]
Coming back to this -- the survey results are shown below, I've summarized the data in a few bullets and included the raw data as well.

* **Do you know how to use the current issue tracker?**
   * Yes - _32.3%_
   * No - _29%_
   * Sort of - _38.7%_
* **Do you like how Minehut Meta is currently set up?**
   * Yes - _29%_
   * No - _54.8%_
   * Undecided - _16.1%_
* **What improvements do you believe came out of switching to this new issue tracker?** _(a summary)_
   * More frequent admin responses
   * Suggestion separation makes it easier for staff members to look at
   * Better organization
     * Better issue tracking
* **What drawbacks do you find while using the new issue tracker?** _(a summary)_
   * Harder identification of people on Discord
   * Preference of Discord
   * GitHub is more complicated than Discord
      * Not friendly for new users
      * Inconvenient 
   * Less activity on GitHub than Discord
* **If Minehut were to go back to using Discord as its issue tracker, how do you think it could be implemented?** _(a summary)_
   * Better way to track suggestions
      * Auto-formatting suggestions
      * Better organization of suggestions
      * Public ticket system with categories such as "Feature Suggestions", "Bug Reports", if something gets denied put it into a denied category and if something is planned put it in a planned category.
   * Having some sort of link between Discord and another service
   * Better moderation of suggestions
* **On a scale of 1 to 10, how likely do you find yourself making a suggestion with this new issue tracker?**
   * ![](https://i.imgur.com/Gbd7VnG.png)
* **On a scale of 1 to 10, how often did you find yourself interacting with a suggestion on Discord?**
   * ![](https://i.imgur.com/PgoWVrs.png)
* **On a scale of 1 to 10, how often did you find yourself interacting with a suggestion on Discord?**
   * ![](https://i.imgur.com/57c52yk.png)
* **On a scale of 1 to 10, how often do you find yourself interacting with a suggestion on GitHub?**
   * ![](https://i.imgur.com/Ib4DN9z.png)
* [Raw Data](https://docs.google.com/spreadsheets/d/13pcX834e6bIZXyQDM_wEdnXHYd9L43fS1qO4Kjfqd4s/edit?usp=sharing)

With this, I believe we should look into exploring better integration of the GitHub API into our Discord bot to make use of what GitHub has to offer and integrating it into Discord. We can always talk about this implementation, however, I don't believe that there's a sufficient way of going back to exclusively Discord. No matter which way we implement it, GitHub offers far more organization and tracking of suggestions and issues that allows developers to actively look into and respond to suggestions and issues. If we were to go back to a Discord exclusive system, we would face the same issues of disorganization with tracking suggestions and their linked conversations. Thus making it extremely more difficult for developers to look at discussion pertaining to a specific suggestion, and would overall just decrease their frequency of responses on suggestions and bug reports.

**Comment by LukasmanMHdude** [comment]
Post this in #announcements pls

**Comment by farwl** [comment]
It's clear and obvious that the great majority wants this change. Minehut Admins have already stated they don't want to move back to Discord because Github is more easier for the development team and better for tracking issues. Someone should probably close this issue.

**Comment by Sniped** [comment]
I'll just go ahead and close this as **wontfix**, in the future I will be prototyping ways we can integrate GitHub into Discord and make the process easier from there, however that will be in its own issue where I note different ways we can integrate both platforms.
