### ISSUE TITLE
Server Queue

### ISSUE THREAD

**Issue by Wryz** [Minehut/Meta#298]
### Feature request

**Checklist**
- [x ] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x ] This is not a bug report, support request or plugin request
- [ x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [ x] This issue does not contain any sensitive information 

**Platform**
 
Java

**Describe the feature**
 
Server Queue:
Right now, if you try to enter a server that is full, you will be sent back to the Minehut lobby. I suggest that Minehut offer a queue that would cost 100-200 credits per server. After purchasing this queue you wait in the lobby until someone in your queued server leaves, then you automatically join that server. If multiple people are in a queue, then the person who has been in the queue the longest will auto join when a free spot opens up. Me personally, I don't like having to sit and reload the server page to join a new server, I'd rather click on it once, and then automatically be sent to the server when a spot opens up

**How the feature is useful**

Minehut heavily depends on the support of server owners to make their money. We see this with the server plans, the catalog, the server slots and the server icons. The only product that is applicable to players are the lobby ranks. 
I think it's reasonable to say that less than 5% of players on Minehut are serious about owning a server, serious enough to even consider upgrading their server plan. That leaves 95% of people who will not spend their money on credits.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by LukasmanMHdude** [comment]
1: Take a look at #253 on how MH makes money, server plans, and whatnot aren't there biggest revenue maker
2: I would not buy this for my server, if I had the credits I would just buy a MH75 plan
3: A lot of people actually use MH as a place to play small SMP's with their friends, I'm not sure where you pulled the 5% number from as many people aspire to create a server. Unless the 5% is server owners with very successful servers with 30 players at peak hours or smth.

**Comment by Shlba** [comment]
Just want to clear up things about my suggestion because I can’t go on my laptop and don’t remember my password.
1. I completely acknowledge my lack of understanding of how Minehut makes it’s money
2. Server queue isn’t something server owners buy, it’s something players can buy for servers they play on frequently
3. Yes, the 5% of people I refer to are the servers that you see on the front page. The 95% are the other players.

Notes: 
I copy pasted the suggestions I wrote before-hand and understand why things could be mixed up, especially since I pasted the context to my suggestion in the ‘reasons why this feature is useful’

Copy and pasted from the discord from @Wryz from the discord. (sent here to be organised)

**Comment by LukasmanMHdude** [comment]
1: Cool, just making sure you knew a bit

2: Makes sense, but servers don't fill up *that* much. I think that a MineHut version of buycraft would be more beneficial to the server.

3: Personally I feel like this would be a waste of development time when there are better features and bugs that need patching

**Comment by Double0negative** [comment]
HI Shlba, thank you for the suggestion. I think its an interesting idea, but dont foresee us implementing it. Theres just not that much of a use-case for this to be worth the development time.
