### ISSUE TITLE
Minehut API?

### ISSUE THREAD

**Issue by ack18** [Minehut/Meta#299]
### Question

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is NOT a Minehut support request

**Question**
When the new Superleague login was added to the Minehut website the `api.minehut.com/users/login` endpoint no longer works (returns `{"error":"No longer supported."`). I can't find any statement on this from Minehut so I'm curious will the API ever be available again/are there any plans to re-open it?

**Comment by 3Q6Dev** [comment]
The new SLG login was added to stop automated programs like the one you are creating. I do not have much hope that the login API will ever be brought back.

**Comment by AdxmGG** [comment]
> The new SLG login was added to stop automated programs like the one you are creating. I do not have much hope that the login API will ever be brought back.

I think the new login was added for security, nothing to do with stopping users being able to create new features for the community...

**Comment by iGalaxyYT** [comment]
theminecoder responded on the current state of the API here: https://github.com/Minehut/Meta/issues/55#issuecomment-683372254

**Comment by Double0negative** [comment]
Hi @ack18, thanks for your interest. Like previous users said, the API change was made for security, SSO, and feature purposes, not to disable 3rd party tools. However, we never actually supported third party tools in the first place and only worked as a side effect of how our old login system worked. Now, in order to support 3rd party tools under the new login system, we would have to manually approve certain tools, meaning that we would officially support these tools/have to have an approval process etc. This is not something that we currently have plans to do at the moment, but something we may re-visit in the future. Closing this issue for now as answered/wont-fix.
