### ISSUE TITLE
Allow /unlink in the lobby

### ISSUE THREAD

**Issue by drtshock** [Minehut/Meta#3]
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**

Website and in game

**Describe the feature**

Allow players to type `/unlink` and then prompt for confirmation to unlink that account from a website account.

**How the feature is useful**

Many users report forgetting which panel account they linked their Minecraft account to, and we cannot give out account information based on a Minecraft username. This will alleviate support tickets as well as make our account linking / unlinking easier.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by farwl** [comment]
Sounds like a useful feature. It would be nice if there was a confirmation prompt for unlinking on the panel as well.

**Comment by awaffle1** [comment]
This is good. I've been waiting for something like this. Currently, there's no way to unlink from a website account you've forgot and it's really annoying.

I'll add to this and say that when you put in the `/link` command and you are linked to another website account, instead of saying that you need to go to the website and unlink, it should tell you that your mc account is linked to another website account and if you want to continue, and to continue it might have you do a command like `/link confirm` or something like that.

**Comment by MiginsMC** [comment]
> Sounds like a useful feature. It would be nice if there was a confirmation prompt for unlinking on the panel as well.

The whole point of this feature is for users who have forgotten the panel account their Minecraft account is linked to. Having a confirmation prompt on the panel seems to remove the point of this feature, especially since you can simply unlink your account through the panel anyway.

**Comment by LukasmanMHdude** [comment]
I saw that this was on the dev server, this is the message I get when running the command lmao:

![image](https://user-images.githubusercontent.com/69743171/97478374-15bee280-190e-11eb-8915-56cff61ebbac.png)

**Comment by Sniped** [comment]
Added in today’s update
