### ISSUE TITLE
Minehut Panel

### ISSUE THREAD

**Issue by ItsMeZeta** [Minehut/Meta#317]
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**
- Website | Minehut Panel

**Describe the feature**

**[Add option for gifting credits]**
- Gifting credits will be only available on purchase 
- OR add a Coupon in shop that cost 6$ to be gifted to another account

_Example_:
>in shop:
>add a Coupon that cost 6$ to be gifted/sent to another account (cannot be refunded)
>on another account:
>when they open that coupon, they will receive 800 Credits (cannot be gifted back)

**[Change Email]**
- Pretty self explanatory

**[Give other player access to your panel]**
- Add trusted member option in panel (allow them to login with their own panel and have access to your panel to modify things)
- This is a risky one, so to remove that risk, allow owner of the panel to set permission like :
>Allow trusted member to paste File : True
>Allow trusted member to delete File : False
>Allow trusted member to delete/reset world: False

**How the feature is useful**

**For the Gifting Credits**: this is a one way to pay your staff on player server as well as you can give it to your friends without logging on to their panel

**For the Change Email**: pretty self explanatory

**For giving access to panel**: Allows server owner to share their panel and allow trusted members to help him and will be less hassle, also if there is a case that the owner can't go on and can't update stuffs such as fixing bug, trusted member can do it for him without giving the whole access to the panel thus preventing cyber security issues

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by PundaChen** [comment]
It's already been confirmed that gifting credits you have in your own account to another user will not happen.
Pretty sure changing email is a dupe.
Subusers are already confirmed to happen soon.

**Comment by ItsMeZeta** [comment]
> It's already been confirmed that gifting credits you have in your own account to another user will not happen.
> Pretty sure changing email is a dupe.
> Subusers are already confirmed to happen soon.

hmm, even for like paying for the credit to be gifted and not gifting the current credit user have?

**Comment by jellz** [comment]
Yeah, email changing is definitely a necessary feature; this was already acknowledged by the Admins. Just need to wait.

In the future, please split up each of your ideas into separate issues, this makes it much easier to vote, discuss and label your ideas - thanks.

**Comment by Shlba** [comment]
Changing email is already a feature that Is being considered, see the community poll from the main discord. It is also a reposted suggestion.

Gifting credits like that would be a hassle since it’s a issue with irl money.

Scenario A) User A buys User B credits, but decides to refund

- what would happen?
- should user B’s credits be deducted? (Note that user B did not expect to lose their credits)

Additionally. I also think that gifting credits alone would allow users to bypass the system set in place by minehut to punish people who buy credits and refund, as said user could hop on an alt, buy credits, refund, and their main account would not be impacted, as it would be near impossible to prove ownership of the accounts

**Comment by ItsMeZeta** [comment]
> Changing email is already a feature that Is being considered, see the community poll from the main discord. It is also a reposted suggestion.
> 
> Gifting credits like that would be a hassle since it’s a issue with irl money.
> 
> Scenario A) User A buys User B credits, but decides to refund
> 
> * what would happen?
> * should user B’s credits be deducted? (Note that user B did not expect to lose their credits)
> 
> Additionally. I also think that gifting credits alone would allow users to bypass the system set in place by minehut to punish people who buy credits and refund, as said user could hop on an alt, buy credits, refund, and their main account would not be impacted, as it would be near impossible to prove ownership of the accounts

hmm, is it possible that the refunding method would only be available through support? like requesting a refund 🤔

**Comment by ItsMeZeta** [comment]
> Yeah, email changing is definitely a necessary feature; this was already acknowledged by the Admins. Just need to wait.
> 
> In the future, please split up each of your ideas into separate issues, this makes it much easier to vote, discuss and label your ideas - thanks.

will take note of this, thank you very much!

**Comment by mrrobboss** [comment]
> * what would happen?
> * should user B’s credits be deducted? (Note that user B did not expect to lose their credits)
I mean it could be like A bought the credits for his account first and then transfers them to B as a separate choice, which then count as "spent" credits so therefore cannot be refunded. Should work only with bought credits as else you can mass vote and transfer to one account.

**Comment by Shlba** [comment]
> hmm, is it possible that the refunding method would only be available through support? like requesting a refund 🤔

No as it’s done via PayPal

**Comment by ItsMeZeta** [comment]
> > hmm, is it possible that the refunding method would only be available through support? like requesting a refund 🤔
> 
> No as it’s done via PayPal

How about in shop for example: 
adding a Coupon that cost 6$ and can be sent to another account (cannot be refunded)

on another account:
when they open that coupon, they will receive 800 Credits (cannot be gifted back)

**Comment by LukasmanMHdude** [comment]
1: Why are you fighting a battle you can't win
2: at this point, the panel needs a full redesign. I think they should honestly just remake it and fix all the issues.

**Comment by Sniped** [comment]
As jellz commented, please split these issues up in the future. It's a lot easier for people to get a brief understanding of your suggestion in your title if you do so. 

Subusers and changing account email are both dupes of two issues:
* Subusers - #13 
* Changing Account Email - #265 

As for gifting credits, with the problem of mass transferring vote credits, maybe in the future Minehut could keep track of what percentage of credits are received from voting and disable them from being gifted. However, gifting credits seems like a lot for the support team to keep track of. With your idea of making coupons that can be gifted, users could just purchase that gift, charge it back, and it would still just give us the same problem of accounts using alts to transfer credits and charging back on their main account. 

If you would like, please make another issue for a credit donation feature. As of right now, I'm going to close this issue since 2/3 of the things you've suggested here are duplicates of another issue.
