### ISSUE TITLE
Black friday sale

### ISSUE THREAD

**Issue by PundaChen** [Minehut/Meta#361]
### Feature request

**Checklist**
- [yes] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [yes] This is not a bug report, support request or plugin request
- [yes] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [yes] This issue does not contain any sensitive information 

**Platform**
 website

**Describe the feature**
 black friday sale on credits when it's black friday

**How the feature is useful**
 more people might buy credits if it's on sale

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by LukasmanMHdude** [comment]
idk why they don't just overprice the credits more then they are and make them always "on sale"

**Comment by DaRealMinecraftexpert** [comment]
I'd be more likely to Buy Credits if the Credit Price was Reduced, not Overpriced.

**Comment by LukasmanMHdude** [comment]
> I'd be more likely to Buy Credits if the Credit Price was Reduced, not Overpriced.

I'm suggesting that the price stay basically the same because there's always a "fall sale" or "black Friday sale" and so on. it would probably help bring in revenue bc ppl would be more likely to buy credits> if they feel an urgency to.

**Comment by killergotrekt** [comment]
Hmmm... uhh sure?

**Comment by Sniped** [comment]
I wouldn't be opposed to seasonal sales, however I don't think that we should overprice credits and then reduce them to make it seem like they're always on sale. While this would make the product more pleasing, the more we have these things on sale the less urgency players would get to buy credits since they know that the sale is either always there or rarely gone.

You submitted a suggestion similar to this one (#143) where you also said that it would be good to use them for a Black Friday sale. Why make this suggestion instead of bringing light to that one?

**Comment by PundaChen** [comment]
Im gonna be completely honest with you facto, I do not remember making that issue because I dont actually check for dupes

**Comment by drtshock** [comment]
We won't be changing the price of credits, but we could make things cost fewer credits.

**Comment by PundaChen** [comment]
Changing the price of credits could benefit Minehut more than changing the prices of things like plans

**Comment by farwl** [comment]
cyber monday sale pls <3

**Comment by theminecoder** [comment]
This isn't the place to ask for sales.

**Comment by Blocksnmore** [comment]
> This isn't the place to ask for sales.

If this isn't then where is

**Comment by LukasmanMHdude** [comment]
^
