### ISSUE TITLE
Server Name Change Feedback

### ISSUE THREAD

**Issue by farwl** [Minehut/Meta#41]
### Feature request

**Platform**
 Website

**Describe the feature**

Add feedback if you changed your server name and it was available. If you change your server name to an unavailable name, it tells you it's unavailable. If you change it to something available, it does nothing. You have to re-enter the server dash to see the changes.

**How the feature is useful**

This is useful if you want to see changes in real time.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by drtshock** [comment]
Makes sense, can definitely give better feedback when doing actions on the website.

**Comment by ZeroParticle** [comment]
Actually, it does auto update already. It just takes about 10 seconds for the change to propagate through the backend. Once the change has been validated it will update on the panel. We could probably add some kind of message to indicate that there are changes pending more generally since the same thing occurs for saving server settings and installing plugins. The validation and propagation time is what makes the panel feel slow to respond.
