### ISSUE TITLE
Skript /server syntax

### ISSUE THREAD

**Issue by Obey23** [Minehut/Meta#484]
### Feature request

**Checklist**
- [Y] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [Y] This is not a bug report, support request or plugin request
- [Y] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [Y] This issue does not contain any sensitive information 

**Platform**

In-game (Skript Plugin Addition)

**Describe the feature**

When (if) Minehut decides to add back the /server command, to be able to interact with it easier and run the bungeecord command, there would have to be a new syntax for it. This could probably, and more than likely, be added to the Skript plugin itself.

**How the feature is useful**

Extremely useful, it allows for sending players between servers on Minehut and better integration of a multi-server "network" of sorts.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by LukasmanMHdude** [comment]
a few logistical things-

1: Transfering of server data. IMO I would probably use this to create multiple instances of the same world that saves data so any1 can join any server with the same progress, but even stuff as simple as ranks would need to get transfered from server to server.

2: Server communication. For example, I shoud be able to send some sort of packet with a player when they switch servers. Even if thats just as simple as adding smth to the players metadata to save on the other server, that would be pog

3: Linking servers. Now, idk if a plan should be needed or not, but I'd assume that mh wants to make money off this lol, just outting it out there. To connect a server, heres a way I thought of.

On the panel under settings or smth, you would be able to add "linked" servers. If the panel is yours, no need to confirm or touch anything. If i isn't, you would need to 1: Confirm the server with the other panel that its ok to connect with and 2: Confirm in email

4: I relize there will probably be an issue with servers all funneling players to one main server, but its late and I can't be bothered to come up with a failsafe atm.

5: Possible code things: *(note that these are just me messing around, playing with ideas)*

**Called when a player is sent from another playerserver** 
```vb
on local server join:
    name of player's [last|previous] server is "azynrpg1"
    message "Hope you had fun on azynrpg! Make sure to check out our other servers!!!"

on local server join:
    if name of player's [last|previous] server isn't "AzynBuild":
        message "Hope you had fun on %player's last server"
    else:
        message "REminder: make sure to submit all your finished builds so a QA can check them"
```

**Sending a player/information to another server**

```vb
command /otherserver:
    send player to local server named "azynhub"

every 5 minutes:
    set all (skript) variables to [all (linked) servers|(linked) servers "name", "name2", and "name3"]

every 2 seconds:
    loop all players:
        sync variable {azynrpg::upcoming_server::level::join_soon::%loop player%} to [all (linked) servers|(linked) servers "name", "name2", and "name3"]
```
"set" means setting the variable on that server to another servers variable. 

"sync" means to set all the variables. in that example, on each server it would loop all players then update the variables on individual playerserves.  This is basically to stop data overwriting. The most recent server would get to rewite the var instead of the one setting it. If 2 servers have diff vars for the same var, ig it'll spit errors in console and just choose whichever? 

aight I know I forget a few things and prolly messed some stuff up, again its late, I'll fix em next morning.

**Comment by LukasmanMHdude** [comment]
added a new type of syntax, LMK what you think...

**Comment by LukasmanMHdude** [comment]
the new one could be useful to have a dev server being able to push to live with a single command, withought having to worry about losing player data. Decided not to include inventories bc you could just sync vars, but looping a whole map and getting it to print right would be a pain. (invs are included in a fulls server push, everything ingame is, even skripts (maybe).

**Comment by honkling** [comment]
I would like to put this out here:
https://skripthub.net/docs/?id=3157

Skript already has the ability to send users to Bungeecord servers, but this doesn't work on Minehut for whatever reason. I'm not sure if the admins explicitly disabled this feature, but they could likely find a way to make it work.

**Comment by LukasmanMHdude** [comment]
> I would like to put this out here:
> https://skripthub.net/docs/?id=3157
> 
> Skript already has the ability to send users to Bungeecord servers, but this doesn't work on Minehut for whatever reason. I'm not sure if the admins explicitly disabled this feature, but they could likely find a way to make it work.

dosen't seem to be the advanced sytaxs listed above, just a connect option. also thats defo disabled

**Comment by Blocksnmore** [comment]
Also that skript syntax would need modifying since iirc minehut doesn’t have the servers be called what you use to join but an id instead.

**Comment by honkling** [comment]
Another edge case Lukas is that when one server wants to pull variables and whatnot from another server, that second server will have to interact with the first server and approve, which could be a bit of a nightmare to tackle from a developer standpoint (for scripters and admins)

**Comment by LukasmanMHdude** [comment]
> Another edge case Lukas is that when one server wants to pull variables and whatnot from another server, that second server will have to interact with the first server and approve, which could be a bit of a nightmare to tackle from a developer standpoint (for scripters and admins)

you would still have to link the servers from the panel, as well as email, so there shouldn't be any issues if thats the implementation. Obvi you cant just steal a server lol.

**Comment by Blocksnmore** [comment]
This could be a setting on a panel, so you can limit what servers interact with each other. This would prevent stuff like brute forcing to modify values.

**Comment by honkling** [comment]
That's a good way of putting it, would definitely be a lot easier to be able to just whitelist servers in the panel

**Comment by LukasmanMHdude** [comment]
also what blocks said, yea. Linked severs could have 3 diff levels of funtionality, ie

| level | name |
| --- | --- |
| handoff | able to send players from one server to another |
 | read | read info from the server (besides worlds & full server copying) |
| everything | all perms lol |

**Comment by LukasmanMHdude** [comment]
unfortuntly this is obays suggestion, so I can't modify it sadly to add this

**Comment by honkling** [comment]
I still believe it's good to discuss ways to implement a feature even if it isn't your issue
What's your thoughts on:
1 - handoff - Transfer players from one server to another
2 - read - Read info from the server (variables, players, etc)
3 - write - Be able to write info to a server. eg. setting variables on another server (perhaps sending messages to players too?)
4 - everything - All perms

also, how can I do that block markdown? Please tell me haha

**Comment by MiginsMC** [comment]
i think every server should have permission to transfer users to other servers by default, maybe this could be disabled in settings?

**Comment by Blocksnmore** [comment]
I feel theres no need in restricting sending players since why would another server send users if its not one of their servers.

**Comment by LukasmanMHdude** [comment]
> i think every server should have permission to transfer users to other servers by default, maybe servers who dont this to happen could disable it somewhere?

yea that could work 


> also, how can I do that block markdown? Please tell me haha

look at discord under the github notifs channel

**Comment by Double0negative** [comment]
Re-adding /server in some fashion is on the roadmap, although I dont have a timeframe right now

**Comment by LukasmanMHdude** [comment]
> Re-adding /server in some fashion is on the roadmap, although I dont have a timeframe right now

planned label o.0?

**Comment by Double0negative** [comment]
> 
> 
> > Re-adding /server in some fashion is on the roadmap, although I dont have a timeframe right now
> 
> planned label o.0?

#119

**Comment by BennyDoesStuff** [comment]
No longer applies after the new server networks update.
