### ISSUE TITLE
Network Kick when disconnected from player server

### ISSUE THREAD

**Issue by farwl** [Minehut/Meta#49]
### Feature request

**Platform**
 in-game / website

**Describe the feature**

Add a setting in the account menu to get completely kicked from the Minehut bungee rather then being sent to the hub if the target server is offline. (And/or make this a setting for your server so that when players connect while it's offline they remain in the multiplayer server list as you would with external servers.) This could also be server-sided so the player server's owner configures it. It could possibly be a premium feature.

**How the feature is useful**

This benefits server owners by giving them more customization.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by drtshock** [comment]
We hear from a lot of users that they actually learned about Minehut when the server they were playing on shut down. I'm not sure we'd want to do this, as this would just be disconnecting users from our network when we can avoid it.

**Comment by Sunni05** [comment]
> We hear from a lot of users that they actually learned about Minehut when the server they were playing on shut down. I'm not sure we'd want to do this, as this would just be disconnecting users from our network when we can avoid it.

Although, how would they have found out about minehut in the first place, they got disconnected to the lobby via the server that was ON minehut. This would still be a very nice feature because some people have custom kick / ban messages due to plugins, and unless your a laggy player like myself, you don’t see the kick message very often, and when your back in the lobby, it sends the /ad message, and clears the chat.
