### ISSUE TITLE
Give us original discordsrv

### ISSUE THREAD

**Issue by Sunni05** [Minehut/Meta#531]
### Feature request

**Checklist**
- [ ] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [ ] This is not a bug report, support request or plugin request
- [ ] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [ ] This issue does not contain any sensitive information 

**Platform**

All
**Describe the feature**

Remove the custom discordsrv and give us the original! I mainly want this because when I go to get support from the disocrdsrc discord, they say they can’t help me because minehut removed the debug command, why debug 😭, yes I know the reason behind it, but if you don’t believe them, check the code. [DiscordSRV Github](https://github.com/DiscordSRV/DiscordSRV/wiki/synchronization)
**How the feature is useful**

This benefits anyone who uses discordsrv.
---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**.

**Comment by LukasmanMHdude** [comment]
1. I asssume thereas a reason why they removed the debug command, but maybe @pop4959 can maybe add it back
2. DiscordSRV has a history of putting, weird stuff inside, "I've had to screen DSRV much more aggressively because they like to hide things in their patches" - **pop4959**#1781, minehut plugin manager
3. They can also use discordsrv to exploit things, which is why it needed to be custom "discordsrv had a feature allowing people to upload any file" - **nitro**#6860, minehut user

**Comment by awaffle1** [comment]
DiscordSRV has a history of being an insecure plugin- personally, I don't like it.

**Comment by Sunni05** [comment]
I have googled a few things, I now see why minehut did that.
