### ISSUE TITLE
Ideas for the Skript plugin

### ISSUE THREAD

**Issue by GearsEngine** [Minehut/Meta#578]
The Skript plugin is so cool, I use it so much for admin tools and new player commands!
It works REALLY well on Minehut, but I think it should have new features because Minehut has it limited _(Note: If I don't realize some removal of features is for security reasons, please tell me!)_

1. Add more 'on command "/whatever":' event functionalty like 'on command "/friend": cancel event', so you could have something like a custom friend system.
2. Maybe remove the /skript:command thing for when you create a command, BUT don't remove things like /skript:skript and /skript:sk.
3. Add more file functionality (I understand that this is a risk, but Minehut can just create their own fork of things, and make it more limited.) Probably should include adding SkUtilities and skript-yaml.
4. Add functionality in vanilla Skript for tablists and scoreboards, I don't want to have to use SkRayFall and SkQuery for these things.
5. Add support for datapacks, so you can just do something like 'command /loadpack: trigger: load datapack from file "https://minehut.com/url/datapack.zip"' I would like this so I don't have to copy and paste my datapacks or use a world upload. (This could be a security risk, because @drtshock has said that .zip files are what .jar files are, but this could be limited to only accept things like .mcfunction files in the .zip.)
6. Add functionality for an arguments list, so you can use 'command /command ["my", "cool", "command"]' to have arguments show up where the command suggestions show up. This is already a thing in the player and offlineplayer argument types but you can't get custom text.

I really hope some of these get added in some way _(If I'm being stupid and some of these features exists already, please tell me!)_

**Comment by quick007YT** [comment]
> Add more 'on command "/whatever":' event functionalty like 'on command "/friend": cancel event', so you could have something like a custom friend system.

We can't remove mh's built in cmds

> Maybe remove the /skript:command thing for when you create a command, BUT don't remove things like /skript:skript and /skript:sk.

you don't need to do that?

> Add more file functionality (I understand that this is a risk, but Minehut can just create their own fork of things, and make it more limited.) Probably should include adding SkUtilities and skript-yaml.

soon:tm:

> Add functionality in vanilla Skript for tablists and scoreboards, I don't want to have to use SkRayFall and SkQuery for these things.
Add support for datapacks, so you can just do something like 'command /loadpack: trigger: load datapack from file "https://minehut.com/url/datapack.zip"' I would like this so I don't have to copy and paste my datapacks or use a world upload. (This could be a security risk, because @drtshock has said that .zip files are what .jar files are, but this could be limited to only accept things like .mcfunction files in the .zip.)
Add functionality for an arguments list, so you can use 'command /command ["my", "cool", "command"]' to have arguments show up where the command suggestions show up. This is already a thing in the player and offlineplayer argument types but you can't get custom text.

ask on https://github.com/SkriptLang/Skript/issues/new?assignees=&labels=&template=suggestion.md
