### ISSUE TITLE
Allow Muted Users to Message Players with Staff Ranks

### ISSUE THREAD

**Issue by BurningBrimstone** [Minehut/Meta#595]
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**

In-Game

**Describe the feature**

Users that have been muted for violating one of many rules should be able to use the (/msg) command to message Helpers, Moderators, and Sr. Moderators despite their muted state. This is in contrast to the traditional behavior that muted users cannot use the (/msg) command at all.

**How the feature is useful**

This feature would allow muted users to be able to ask volunteer staff why they were muted, so they are able to recognize the behavior as unacceptable as well as ask volunteer staff how to appeal their punishment. Volunteer staff will still be able to (/ignore) users should they begin using the message permission to harass the staff member.

**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by quick007** [comment]
No, the staff member that muted them just needs to give a better synopsis of why they were muted. They don't appeal in the staff member's DM's. Also, if I was a staff member and got my DM's spammed every time I muted a bitter I would be mad.

**Comment by BurningBrimstone** [comment]
> 
> 
> No, the staff member that muted them just needs to give a better synopsis of why they were muted. They don't appeal in the staff member's DM's. Also, if I was a staff member and got my DM's spammed every time I muted a bitter I would be mad.

Punishment reasons are predetermined, so staff do not have the ability to "give a better synopsis of why they were muted", and some users are not aware of **how** to appeal, in which case the staff member would be able to redirect them to the appeals section of the forums. Regarding your last objection, yes, that is true. However, as I mentioned in my post staff members would still be able to /ignore users, atleast partially mitigating that issue.

**Comment by quick007** [comment]
> However, as I mentioned in my post staff members would still be able to /ignore users, atleast partially mitigating that issue.

ah yes, staff members need to /ignore & relog every time they mute someone and they start spamming their DM's

> Punishment reasons are predetermined,

Thats an issue with the system, which means we should fix that problem rather than adding on another feature

> some users are not aware of how to appeal, 

confused on why the appeal link isn't included when there muted & whenever they try to talk

again, many of these issues are with the system itself, not weather or not ppl can msg staff

**Comment by CoreyShupe** [comment]
> > No, the staff member that muted them just needs to give a better synopsis of why they were muted. They don't appeal in the staff member's DM's. Also, if I was a staff member and got my DM's spammed every time I muted a bitter I would be mad.
> 
> Punishment reasons are predetermined, so staff do not have the ability to "give a better synopsis of why they were muted", and some users are not aware of **how** to appeal, in which case the staff member would be able to redirect them to the appeals section of the forums. Regarding your last objection, yes, that is true. However, as I mentioned in my post staff members would still be able to /ignore users, atleast partially mitigating that issue.

This seems like a bad tradeoff. If you don't think there's a good punishment reason which fits a specific purpose you should suggest one. Most punishment reasons are pretty specific (spam/flood/caps), you kind of know what you're doing. For thing like external ads, etc... you can appeal those kinds of things.

If you feel like there's not enough explanation on the side of how to appeal and such, suggest adding it into the message we send to the user. Some of the punishments do have this sent but not all of them. Definitely if you feel like there's not enough information being sent I'd like to see the cases in which a user is punished and bewildered about why considering we have pretty targeted punishment reasons.

I think there's some punishments which may have question like harassment or what-not but I think those happen in a frequency which can be handled on a case-by-case basis. Also, they don't know which staff punished them so they can't really make a clear decision on who to message, you may be seeing a bitter muted person spam the dms of a different staff member simply because they're high ranking and have a rank, this could be problematic. There's also an /appeal command which they can use (I believe). Obviously this might be nice to send in the mute message, we'd just need to discuss it in the staff team.

All-in-all I recommend bringing this issue up with Benny. I don't think the correct way is to allow them to just message staff, sometimes I mute because people message me certain things. Obviously there's ignoring but again, it's less than convenient in the time especially when doing things, or when somebody is being extremely inappropriate.

Also, in the case where this one person doesn't like the fact they're muted why would they stop with one staff member? I don't think we should expect all staff to /ignore a single person when they're already muted just because they're unhappy. We should be properly redirecting people to proper places to appeal and whatnot.

**Comment by BurningBrimstone** [comment]
> Also, in the case where this one person doesn't like the fact they're muted why would they stop with one staff member? I don't think we should expect all staff to /ignore a single person when they're already muted just because they're unhappy. We should be properly redirecting people to proper places to appeal and whatnot.

Fair enough. I'll work on other requests regarding "better" punishment messages as to reduce potential confusion and notify users of the appeals option. 

That's a pretty conclusive answer to the suggestion, and public reception was mixed at best, so I'll be closing this.
