### ISSUE TITLE
Please remove the asterisk from the bedrock username.

### ISSUE THREAD

**Issue by CrystalLiquid3** [Minehut/Meta#698]
### Bug report

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] I am NOT reporting a security vulnerability
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information

**Platform**

In-game Bedrock but everything is affected by the bug in the bedrock username/account.

**Describe the bug**

I own a server with my friends and about half of my friends are on bedrock. When I try to /tp to them it says "Invalid username or UUID". It may not be the actual asterisk and be something with the bedrock account itself but it happens with everybody with an asterisk. The only command that works for some reason is /ban. /kill, /effect, nor /kick work. I am always forced to use /command @r... instead of their username.

**To reproduce**
Steps to reproduce the behaviour:
1. Find a person with an asterisk at the start of their name
2. Do any command other than /ban on them and use their actual name - example: /kill *player

**Expected behaviour**

After pressing enter and sending the command into chat, all it says is "Invalid username or UUID" in red text.

**Device Information**

- Minecraft Client (and version): Java 1.17.1
- Web browser (and version): N/A
- Operating system (and version): MACOS Mojave 10.14.6

**Screenshots**

**Additional context**

---
**Try to reproduce this bug and let us know in the comments if you can reproduce it or not. Make sure to include your relevant device information!**

**Comment by drtshock** [comment]
The issue with this is that there could be name collisions between bedrock and java users then. And Bedrock users don't have valid Java UUIDs. This is just an issue with having bedrock users join java servers, and the java servers only know to expect java users. The best way around this imo is to use a script or another plugin that knows how to handle bedrock users.

We just ran a private build competition that was cross platform, and had to write a custom script to manage the whitelist since Minecraft's whitelist can't handle bedrock users.

**Comment by CrystalLiquid3** [comment]
Ah ok. Thanks for reviewing my form.
