### ISSUE TITLE
Text basically overtyping other text

### ISSUE THREAD

**Issue by emopedia** [Minehut/Meta#801]
### Bug report

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] I am NOT reporting a security vulnerability
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information

**Platform**

Website

**Describe the bug**

Text basically overtypes over other text, making text after text you are typing disappear (prob suck at saying that but ehh)

**To reproduce**
Steps to reproduce the behaviour:
1. Go to a file (not sure if this happens for other files other than skripts)
2. Remove a section of a line and leave some ahead of you
3. Start typing before that left over code

**Expected behaviour**

It to like well, be normal and move instead of just vanishing basically (god i suck at explaining)

**Device Information**

- Minecraft client (and version): Not applicable
- Web browser (and version): Brave 1.29.81
- Operating system (and version): Windows 10 Pro 19043.1237
- Minehut server name: Not applicable

**Screenshots**

https://user-images.githubusercontent.com/76584247/135209353-3f66bb51-275e-4e21-a51d-ae32c98bda37.mp4

**Additional context**

---
**Try to reproduce this bug and let us know in the comments if you can reproduce it or not. Make sure to include your relevant device information!**

**Comment by MrTibo1** [comment]
Insert key to toggle

**Comment by emopedia** [comment]
> Insert key to toggle

doesn't fix it for some reason

**Comment by tarna** [comment]
Can't replicate. And you probably have overtype mode enabled. Pressing the insert should have fixed it. Because I can replicate this after I pressed insert to enable overtype mode. If you are using a laptop, make sure to press shift with the insert key on the numpad area for it to work.

If it's only doing this for you on the Minehut file manager, then it may be an issue with that but if its doing it in other places too, it's probably cause of overtype mode.

**Comment by CoreyShupe** [comment]
#854
