### ISSUE TITLE
Minehut Panel Issue

### ISSUE THREAD

**Issue by Nopock** [Minehut/Meta#947]
### Bug report

**Checklist**
- [ ] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [ ] I am NOT reporting a security vulnerability
- [ ] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [ ] This issue does not contain any sensitive information

**Platform**

**Device Information**

- Minecraft client (and version): 
- Web browser (and version): 
- Operating system (and version): 
- Minehut server name: 

**Screenshots**

**Additional context**

---
**Try to reproduce this bug and let us know in the comments if you can reproduce it or not. Make sure to include your relevant device information!**

**Comment by tarna** [comment]
Not sure if you accidentally put the description in a comment cause its not shown here but is shown in the #issues channel in the Meta Discord. But looking at the part of the bug description that I see in the Discord, looks like you may be talking about the issue where the panel spam logs in and out. That issue was already sent out in the #updates channel on the main Discord and clearing your browser cookies for Minehut should fix this for now.

**Comment by Nopock** [comment]
> 

Yeah I am currently banned from the mh discord so I can't view that
